# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _mcc3aa680d110b2cef781526b89cd7469
else:
    import _mcc3aa680d110b2cef781526b89cd7469

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_SwigPyIterator

    def value(self):
        return _mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator_equal(self, x)

    def copy(self):
        return _mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator_copy(self)

    def next(self):
        return _mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator_next(self)

    def __next__(self):
        return _mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator___next__(self)

    def previous(self):
        return _mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator_previous(self)

    def advance(self, n):
        return _mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.SwigPyIterator_swigregister(SwigPyIterator)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    all_keys = [attr for attr in dir(class_type) if not attr.startswith('__')and attr != '_s' ]
    data_keys = sorted(class_type.__swig_setmethods__.keys())
    method_keys = [ x for x in all_keys if x not in data_keys ]
    raise AttributeError("Type %s does not contain member %s.\n%s data = %s\n%s methods = %s" %
     (self.__class__.__name__,name,self.__class__.__name__,data_keys,self.__class__.__name__,method_keys))

def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
# this line is changed to handle older swigs that used PySwigObject instead of the current SwigPyObject
        if type(value).__name__ == 'SwigPyObject' or type(value).__name__ == 'PySwigObject' :
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        all_keys = [attr for attr in dir(class_type) if not attr.startswith('__') and attr != '_s' ]
        data_keys = sorted(class_type.__swig_setmethods__.keys())
        method_keys = [ x for x in all_keys if x not in data_keys ]
        raise AttributeError("Type %s does not contain member %s.\n%s data = %s\n%s methods = %s" %
         (self.__class__.__name__,name,self.__class__.__name__,data_keys,self.__class__.__name__,method_keys))

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,1)

import sim_services
import m2d7c369471cac3e20a0505ea0a9f0f94
class SimEnvironment(sim_services.Environment):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)


    def __init__(self, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_SimEnvironment()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "SimEnvironment", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.SimEnvironment___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.SimEnvironment___len__(self, *args)
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_SimEnvironment

# Register SimEnvironment in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.SimEnvironment_swigregister(SimEnvironment)

def exec_collect_init(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.exec_collect_init(*args)
class SysSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    sched = property(_mcc3aa680d110b2cef781526b89cd7469.SysSimObject_sched_get)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_SysSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "SysSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.SysSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.SysSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.SysSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.SysSimObject___len__(self, *args)
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_SysSimObject

# Register SysSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.SysSimObject_swigregister(SysSimObject)
class MemoryManagerSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    mm = property(_mcc3aa680d110b2cef781526b89cd7469.MemoryManagerSimObject_mm_get, _mcc3aa680d110b2cef781526b89cd7469.MemoryManagerSimObject_mm_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_MemoryManagerSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MemoryManagerSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.MemoryManagerSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.MemoryManagerSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.MemoryManagerSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.MemoryManagerSimObject___len__(self, *args)
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_MemoryManagerSimObject

# Register MemoryManagerSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.MemoryManagerSimObject_swigregister(MemoryManagerSimObject)
class CheckPointRestartSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    cpr = property(_mcc3aa680d110b2cef781526b89cd7469.CheckPointRestartSimObject_cpr_get, _mcc3aa680d110b2cef781526b89cd7469.CheckPointRestartSimObject_cpr_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_CheckPointRestartSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "CheckPointRestartSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.CheckPointRestartSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.CheckPointRestartSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.CheckPointRestartSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.CheckPointRestartSimObject___len__(self, *args)
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_CheckPointRestartSimObject

# Register CheckPointRestartSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.CheckPointRestartSimObject_swigregister(CheckPointRestartSimObject)
class SieSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    sie = property(_mcc3aa680d110b2cef781526b89cd7469.SieSimObject_sie_get, _mcc3aa680d110b2cef781526b89cd7469.SieSimObject_sie_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_SieSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "SieSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.SieSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.SieSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.SieSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.SieSimObject___len__(self, *args)
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_SieSimObject

# Register SieSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.SieSimObject_swigregister(SieSimObject)
class CommandLineArgumentsSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    cmd_args = property(_mcc3aa680d110b2cef781526b89cd7469.CommandLineArgumentsSimObject_cmd_args_get, _mcc3aa680d110b2cef781526b89cd7469.CommandLineArgumentsSimObject_cmd_args_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_CommandLineArgumentsSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "CommandLineArgumentsSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.CommandLineArgumentsSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.CommandLineArgumentsSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.CommandLineArgumentsSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.CommandLineArgumentsSimObject___len__(self, *args)
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_CommandLineArgumentsSimObject

# Register CommandLineArgumentsSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.CommandLineArgumentsSimObject_swigregister(CommandLineArgumentsSimObject)
class MessageSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    mpublisher = property(_mcc3aa680d110b2cef781526b89cd7469.MessageSimObject_mpublisher_get, _mcc3aa680d110b2cef781526b89cd7469.MessageSimObject_mpublisher_set)
    mcout = property(_mcc3aa680d110b2cef781526b89cd7469.MessageSimObject_mcout_get, _mcc3aa680d110b2cef781526b89cd7469.MessageSimObject_mcout_set)
    mtcout = property(_mcc3aa680d110b2cef781526b89cd7469.MessageSimObject_mtcout_get, _mcc3aa680d110b2cef781526b89cd7469.MessageSimObject_mtcout_set)
    mfile = property(_mcc3aa680d110b2cef781526b89cd7469.MessageSimObject_mfile_get)
    mdevice = property(_mcc3aa680d110b2cef781526b89cd7469.MessageSimObject_mdevice_get, _mcc3aa680d110b2cef781526b89cd7469.MessageSimObject_mdevice_set)
    pfile = property(_mcc3aa680d110b2cef781526b89cd7469.MessageSimObject_pfile_get)
    message_file_manager = property(_mcc3aa680d110b2cef781526b89cd7469.MessageSimObject_message_file_manager_get, _mcc3aa680d110b2cef781526b89cd7469.MessageSimObject_message_file_manager_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_MessageSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MessageSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.MessageSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.MessageSimObject_call_function_double(self, *args)

    def separate_thread_set_enabled(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.MessageSimObject_separate_thread_set_enabled(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.MessageSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.MessageSimObject___len__(self, *args)
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_MessageSimObject

# Register MessageSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.MessageSimObject_swigregister(MessageSimObject)
class JITSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    jit = property(_mcc3aa680d110b2cef781526b89cd7469.JITSimObject_jit_get, _mcc3aa680d110b2cef781526b89cd7469.JITSimObject_jit_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_JITSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "JITSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.JITSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.JITSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.JITSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.JITSimObject___len__(self, *args)
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_JITSimObject

# Register JITSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.JITSimObject_swigregister(JITSimObject)
class InputProcessorSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    ip = property(_mcc3aa680d110b2cef781526b89cd7469.InputProcessorSimObject_ip_get, _mcc3aa680d110b2cef781526b89cd7469.InputProcessorSimObject_ip_set)
    mtv = property(_mcc3aa680d110b2cef781526b89cd7469.InputProcessorSimObject_mtv_get, _mcc3aa680d110b2cef781526b89cd7469.InputProcessorSimObject_mtv_set)
    units_map_ptr = property(_mcc3aa680d110b2cef781526b89cd7469.InputProcessorSimObject_units_map_ptr_get, _mcc3aa680d110b2cef781526b89cd7469.InputProcessorSimObject_units_map_ptr_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_InputProcessorSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "InputProcessorSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW


    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_InputProcessorSimObject

    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.InputProcessorSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.InputProcessorSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.InputProcessorSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.InputProcessorSimObject___len__(self, *args)

# Register InputProcessorSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.InputProcessorSimObject_swigregister(InputProcessorSimObject)
class ThreadProcessEventSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    ep = property(_mcc3aa680d110b2cef781526b89cd7469.ThreadProcessEventSimObject_ep_get, _mcc3aa680d110b2cef781526b89cd7469.ThreadProcessEventSimObject_ep_set)

    def __init__(self, *args, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_ThreadProcessEventSimObject(*args)
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            this.own(0)
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "ThreadProcessEventSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.ThreadProcessEventSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.ThreadProcessEventSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.ThreadProcessEventSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.ThreadProcessEventSimObject___len__(self, *args)
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_ThreadProcessEventSimObject

# Register ThreadProcessEventSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.ThreadProcessEventSimObject_swigregister(ThreadProcessEventSimObject)
class EventManagerSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    em = property(_mcc3aa680d110b2cef781526b89cd7469.EventManagerSimObject_em_get, _mcc3aa680d110b2cef781526b89cd7469.EventManagerSimObject_em_set)
    ep = property(_mcc3aa680d110b2cef781526b89cd7469.EventManagerSimObject_ep_get, _mcc3aa680d110b2cef781526b89cd7469.EventManagerSimObject_ep_set)
    thread_process_event_so = property(_mcc3aa680d110b2cef781526b89cd7469.EventManagerSimObject_thread_process_event_so_get, _mcc3aa680d110b2cef781526b89cd7469.EventManagerSimObject_thread_process_event_so_set)
    thread_process_event_so_names = property(_mcc3aa680d110b2cef781526b89cd7469.EventManagerSimObject_thread_process_event_so_names_get, _mcc3aa680d110b2cef781526b89cd7469.EventManagerSimObject_thread_process_event_so_names_set)

    def create_thread_process_event(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.EventManagerSimObject_create_thread_process_event(self, *args)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_EventManagerSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "EventManagerSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW


    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_EventManagerSimObject

    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.EventManagerSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.EventManagerSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.EventManagerSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.EventManagerSimObject___len__(self, *args)

# Register EventManagerSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.EventManagerSimObject_swigregister(EventManagerSimObject)
class VariableServerSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    vs = property(_mcc3aa680d110b2cef781526b89cd7469.VariableServerSimObject_vs_get, _mcc3aa680d110b2cef781526b89cd7469.VariableServerSimObject_vs_set)
    sim_control_panel = property(_mcc3aa680d110b2cef781526b89cd7469.VariableServerSimObject_sim_control_panel_get)
    trick_view = property(_mcc3aa680d110b2cef781526b89cd7469.VariableServerSimObject_trick_view_get)
    malfunctions_trick_view = property(_mcc3aa680d110b2cef781526b89cd7469.VariableServerSimObject_malfunctions_trick_view_get)
    stripchart = property(_mcc3aa680d110b2cef781526b89cd7469.VariableServerSimObject_stripchart_get)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_VariableServerSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "VariableServerSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.VariableServerSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.VariableServerSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.VariableServerSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.VariableServerSimObject___len__(self, *args)
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_VariableServerSimObject

# Register VariableServerSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.VariableServerSimObject_swigregister(VariableServerSimObject)
class DataRecordDispatcherSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    drd = property(_mcc3aa680d110b2cef781526b89cd7469.DataRecordDispatcherSimObject_drd_get)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_DataRecordDispatcherSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "DataRecordDispatcherSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.DataRecordDispatcherSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.DataRecordDispatcherSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.DataRecordDispatcherSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.DataRecordDispatcherSimObject___len__(self, *args)
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_DataRecordDispatcherSimObject

# Register DataRecordDispatcherSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.DataRecordDispatcherSimObject_swigregister(DataRecordDispatcherSimObject)
class RTSyncSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    gtod_clock = property(_mcc3aa680d110b2cef781526b89cd7469.RTSyncSimObject_gtod_clock_get, _mcc3aa680d110b2cef781526b89cd7469.RTSyncSimObject_gtod_clock_set)
    itimer = property(_mcc3aa680d110b2cef781526b89cd7469.RTSyncSimObject_itimer_get, _mcc3aa680d110b2cef781526b89cd7469.RTSyncSimObject_itimer_set)
    rt_sync = property(_mcc3aa680d110b2cef781526b89cd7469.RTSyncSimObject_rt_sync_get, _mcc3aa680d110b2cef781526b89cd7469.RTSyncSimObject_rt_sync_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_RTSyncSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "RTSyncSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.RTSyncSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.RTSyncSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.RTSyncSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.RTSyncSimObject___len__(self, *args)
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_RTSyncSimObject

# Register RTSyncSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.RTSyncSimObject_swigregister(RTSyncSimObject)
class FrameLogSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    frame_log = property(_mcc3aa680d110b2cef781526b89cd7469.FrameLogSimObject_frame_log_get)

    def __init__(self, *args, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_FrameLogSimObject(*args)
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            this.own(0)
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "FrameLogSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.FrameLogSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.FrameLogSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.FrameLogSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.FrameLogSimObject___len__(self, *args)
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_FrameLogSimObject

# Register FrameLogSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.FrameLogSimObject_swigregister(FrameLogSimObject)
class UnitTestSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    unit_tests = property(_mcc3aa680d110b2cef781526b89cd7469.UnitTestSimObject_unit_tests_get, _mcc3aa680d110b2cef781526b89cd7469.UnitTestSimObject_unit_tests_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_UnitTestSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "UnitTestSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.UnitTestSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.UnitTestSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.UnitTestSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.UnitTestSimObject___len__(self, *args)
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_UnitTestSimObject

# Register UnitTestSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.UnitTestSimObject_swigregister(UnitTestSimObject)
class UdUnitsSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    udunits = property(_mcc3aa680d110b2cef781526b89cd7469.UdUnitsSimObject_udunits_get, _mcc3aa680d110b2cef781526b89cd7469.UdUnitsSimObject_udunits_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_UdUnitsSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "UdUnitsSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.UdUnitsSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.UdUnitsSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.UdUnitsSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.UdUnitsSimObject___len__(self, *args)
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_UdUnitsSimObject

# Register UdUnitsSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.UdUnitsSimObject_swigregister(UdUnitsSimObject)
class SatelliteSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    satellite = property(_mcc3aa680d110b2cef781526b89cd7469.SatelliteSimObject_satellite_get, _mcc3aa680d110b2cef781526b89cd7469.SatelliteSimObject_satellite_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcc3aa680d110b2cef781526b89cd7469.new_SatelliteSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "SatelliteSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.SatelliteSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.SatelliteSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.SatelliteSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcc3aa680d110b2cef781526b89cd7469.SatelliteSimObject___len__(self, *args)
    __swig_destroy__ = _mcc3aa680d110b2cef781526b89cd7469.delete_SatelliteSimObject

# Register SatelliteSimObject in _mcc3aa680d110b2cef781526b89cd7469:
_mcc3aa680d110b2cef781526b89cd7469.SatelliteSimObject_swigregister(SatelliteSimObject)

def castAsSimEnvironment(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsSimEnvironment(*args)

def castAsSysSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsSysSimObject(*args)

def castAsMemoryManagerSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsMemoryManagerSimObject(*args)

def castAsCheckPointRestartSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsCheckPointRestartSimObject(*args)

def castAsSieSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsSieSimObject(*args)

def castAsCommandLineArgumentsSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsCommandLineArgumentsSimObject(*args)

def castAsMessageSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsMessageSimObject(*args)

def castAsJITSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsJITSimObject(*args)

def castAsInputProcessorSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsInputProcessorSimObject(*args)

def castAsThreadProcessEventSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsThreadProcessEventSimObject(*args)

def castAsEventManagerSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsEventManagerSimObject(*args)

def castAsVariableServerSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsVariableServerSimObject(*args)

def castAsDataRecordDispatcherSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsDataRecordDispatcherSimObject(*args)

def castAsRTSyncSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsRTSyncSimObject(*args)

def castAsFrameLogSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsFrameLogSimObject(*args)

def castAsUnitTestSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsUnitTestSimObject(*args)

def castAsUdUnitsSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsUdUnitsSimObject(*args)

def castAsSatelliteSimObject(*args):
    return _mcc3aa680d110b2cef781526b89cd7469.castAsSatelliteSimObject(*args)

